server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8

spring:
  http:
    encoding:
      charset: UTF-8
  # 数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/easy?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    root: INFO
    easy.lilm.p: INFO
    org.springframework.web: INFO
  file: logs/web.log

